# frozen_string_literal: true

module RussianSuspensionTranslations
  MAP = {
    "CFMOTO Asqı Tənzimləmə Kalkulyatoru | Azərbaycan" => "Калькулятор настройки подвески CFMOTO | Азербайджан",
    "CFMOTO motosikletləri üçün model, yük və sürüş şəraitinə uyğun ön və arxa asqı sazlamalarını hesablayın." => "Рассчитайте начальные настройки передней и задней подвески CFMOTO с учётом модели, нагрузки и условий движения.",
    "CFMOTO asqı tənzimləmə kalkulyatoru" => "Калькулятор настройки подвески CFMOTO",
    "Məlumatlandırma və sazlama aləti" => "Информационный инструмент настройки",
    "Modeli, real yükü və sürüş şəraitini seçin; rəsmi istifadəçi təlimatlarındakı cədvəllər əsasında ön və arxa asqı üçün başlanğıc dəyərlərini dərhal görün." => "Выберите модель, фактическую нагрузку и условия движения, чтобы сразу получить начальные настройки передней и задней подвески по таблицам из официальных руководств пользователя.",
    "Kalkulyatorun işləməsi üçün JavaScript aktiv olmalıdır." => "Для работы калькулятора необходимо включить JavaScript.",
    "Bu kalkulyator nə edir?" => "Что делает этот калькулятор?",
    "Alət seçilmiş CFMOTO modelinin istifadəçi təlimatında dərc olunan asqı cədvəllərini rəqəmsal formaya çevirir. Sürücü, sərnişin və baqaj çəkisini daxil etdikdə ümumi yük hesablanır, sonra cədvəldəki ən yaxın iki rəsmi yük nöqtəsi arasında xətti hesablama aparılır. Nəticə tənzimləyicinin real addımına uyğun olaraq kliklər üçün tam ədədə, dövr və millimetr üçün yarım addıma yuvarlaqlaşdırılır." => "Инструмент переводит в цифровой формат таблицы подвески, опубликованные в руководстве пользователя выбранной модели CFMOTO. После ввода веса водителя, пассажира и багажа рассчитывается общая нагрузка, затем выполняется линейный расчёт между двумя ближайшими официальными точками нагрузки. Результат округляется с учётом реального шага регулировки: клики — до целого, обороты и миллиметры — до половины шага.",
    "Rəsmi cədvəlin aşağı və ya yuxarı sərhədi keçildikdə kalkulyator yeni dəyər uydurmur; ən yaxın sənədləşdirilmiş sazlamanı saxlayır və ekranda xəbərdarlıq göstərir. Modelin icazə verilən yük həddi, konkret bazar versiyası və istehsal ili üzrə istifadəçi təlimatı həmişə əsas mənbədir." => "Если нагрузка выходит ниже или выше границ официальной таблицы, калькулятор не придумывает новое значение: он сохраняет ближайшую документированную настройку и показывает предупреждение. Главным источником всегда остаётся руководство пользователя для конкретного года выпуска и рыночной версии, включая допустимую нагрузку модели.",
    "Hesablama qaydası" => "Как выполняется расчёт",
    "Motosiklet modelini və sürüş rejimini seçin." => "Выберите модель мотоцикла и режим движения.",
    "Tək, baqajlı və ya sərnişinli istifadə ssenarisini qeyd edin." => "Укажите сценарий: один водитель, с багажом или с пассажиром.",
    "Faktiki çəkiləri qoruyucu geyim və daşınan əşyalarla birlikdə daxil edin." => "Введите фактический вес с учётом экипировки и перевозимых вещей.",
    "Ön və arxa asqı nəticələrini, sayma istiqamətini və hesablamanın izahını yoxlayın." => "Проверьте значения передней и задней подвески, направление отсчёта и объяснение расчёта.",
    "Nəticəni necə tətbiq etməli?" => "Как применять результат?",
    "Motosikleti düz və sabit səthdə saxlayın, mühərriki söndürün və hər dəyişiklikdən əvvəl mövcud sazlamanı qeyd edin. Sol və sağ ön amortizatorlar ayrıca tənzimlənirsə, hər iki tərəfdə eyni dəyəri seçin. Tənzimləyicini son nöqtədə zorlamayın; yüngül dayanmaya çatdıqda kalkulyatorda göstərilən istiqamətdə saymağa başlayın. Bir dəfəyə yalnız bir parametr dəyişin və qısa, təhlükəsiz test yürüşü ilə nəticəni qiymətləndirin." => "Установите мотоцикл на ровной устойчивой поверхности, выключите двигатель и перед каждым изменением запишите текущую настройку. Если левая и правая передние стойки регулируются отдельно, установите одинаковое значение с обеих сторон. Не прилагайте усилие к регулятору в крайнем положении: после лёгкого упора начинайте отсчёт в направлении, указанном калькулятором. Меняйте только один параметр за раз и оценивайте результат во время короткой безопасной пробной поездки.",
    "Asqı motosikletin sabitliyinə, əyləcləmə davranışına və təkərin yol ilə təmasına təsir edir. Qeyri-adi səs, yağ sızması, zədələnmiş detal, idarəetmədə qeyri-sabitlik və ya sazlama addımlarının uyğun gəlməməsi müşahidə olunursa, sürüşü dayandırın və rəsmi servisə müraciət edin. SAG ölçümü və fərdi sazlama üçün peşəkar texnik dəstəyi daha dəqiq nəticə verir." => "Подвеска влияет на устойчивость мотоцикла, поведение при торможении и контакт шин с дорогой. При необычном шуме, утечке масла, повреждении деталей, нестабильном управлении или несовпадении числа регулировочных шагов прекратите поездку и обратитесь в официальный сервис. Для измерения SAG и индивидуальной настройки точнее воспользоваться помощью профессионального техника.",
    "Niyə bütün modellər siyahıda deyil?" => "Почему в списке есть не все модели?",
    "İlk versiyada yalnız Azərbaycan kataloqunda olan və sazlama cədvəli rəsmi təlimatda təsdiqlənən 1000MT-X, 800MT-X, 800MT SPORT, 800MT EXPLORE, 700MT və 450MT modelləri göstərilir. Tənzimlənməyən və ya yükə görə rəsmi cədvəli olmayan amortizatorlar üçün təxmini rəqəm təqdim edilmir. Digər modellər yalnız uyğun təlimat və yerli komplektasiya yoxlandıqdan sonra əlavə olunacaq." => "В первой версии показаны только представленные в каталоге Азербайджана модели 1000MT-X, 800MT-X, 800MT SPORT, 800MT EXPLORE, 700MT и 450MT, для которых таблица регулировок подтверждена официальным руководством. Для нерегулируемых узлов или подвески без официальной таблицы по нагрузке приблизительные значения не выдаются. Другие модели будут добавлены только после проверки соответствующего руководства и местной комплектации.",
    "Bu nəticələr başlanğıc nöqtəsidir, servis diaqnostikasını və motosikletinizin istifadəçi təlimatını əvəz etmir. Model ili və komplektasiyaya görə fərqlər mümkündür." => "Эти результаты служат отправной точкой и не заменяют сервисную диагностику и руководство пользователя вашего мотоцикла. Возможны различия в зависимости от года выпуска и комплектации.",
    "Tez-tez verilən suallar" => "Часто задаваемые вопросы",
    "Dəyərlər rəsmi zavod məlumatıdır?" => "Значения основаны на заводских данных?",
    "Hesablamanın dayaq nöqtələri CFMOTO istifadəçi təlimatlarındakı sazlama cədvəllərindən götürülür. Aralıq çəkilər üçün göstərilən nəticə həmin rəsmi nöqtələr arasında hesablanan başlanğıc dəyəridir." => "Опорные точки расчёта взяты из таблиц настройки в руководствах пользователя CFMOTO. Для промежуточного веса показывается начальное значение, рассчитанное между этими официальными точками.",
    "Niyə nəticə çəkini dəyişdikcə yenilənir?" => "Почему результат меняется вместе с весом?",
    "Asqının daşıdığı ümumi yük dəyişdikcə uyğun iki cədvəl sətri arasında proporsional hesab aparılır. Beləliklə yalnız dörd standart ssenari ilə məhdudlaşmadan real yükünüzə daha yaxın başlanğıc sazlaması əldə edilir." => "При изменении общей нагрузки на подвеску выполняется пропорциональный расчёт между двумя подходящими строками таблицы. Поэтому начальная настройка лучше соответствует фактической нагрузке, а не ограничивается четырьмя стандартными сценариями.",
    "Yolsuzluq rejimi bütün modellərdə işləyir?" => "Режим плохой дороги доступен для всех моделей?",
    "Xeyr. Bu seçim yalnız rəsmi təlimatda davamlı pis yol və ya yüngül yolsuzluq üçün ayrıca sətr olan modellərdə göstərilir. Digər modellər üçün təsdiqlənməmiş yumşaltma və ya sərtləşdirmə tətbiq edilmir." => "Нет. Этот выбор показывается только для моделей, в официальном руководстве которых есть отдельная строка для длительной плохой дороги или лёгкого бездорожья. Для остальных моделей неподтверждённое смягчение или ужесточение не применяется.",
    "Yük cədvəldəki maksimumdan çox olarsa nə baş verir?" => "Что происходит, если нагрузка выше максимума таблицы?",
    "Kalkulyator ən yüksək rəsmi cədvəl sətrini saxlayır və xəbərdarlıq verir. Bu, motosikletin icazə verilən maksimum yükü demək deyil; yük limitini ayrıca istifadəçi təlimatından yoxlayın." => "Калькулятор сохраняет самую высокую официальную строку таблицы и показывает предупреждение. Это не означает допустимую максимальную нагрузку мотоцикла; предел нагрузки следует отдельно проверить в руководстве пользователя.",
    "Rəsmi servis ilə sazlamanı dəqiqləşdirin" => "Уточните настройку в официальном сервисе",
    "Model ili, yerli komplektasiya və faktiki SAG ölçüsünə uyğun fərdi yoxlama üçün servis komandası ilə əlaqə saxlayın." => "Свяжитесь с сервисной командой для индивидуальной проверки с учётом года выпуска, местной комплектации и фактического измерения SAG.",
    "Servisə zəng et" => "Позвонить в сервис"
  }.freeze
end
